project_id = "krphczarhjtnbqlyhfsn"

[functions.calculate-due-date]
verify_jwt = false

[functions.healthcare-recommendations]
verify_jwt = true

[functions.analyze-symptom]
verify_jwt = true

[functions.check-drug-safety]
verify_jwt = true

[functions.admin-register]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-campaigns]
verify_jwt = false
